### ISSUE TITLE
The following _CastError was thrown resolving an image codec

### ISSUE THREAD

**Issue by alexgrusu43** [stelynx/network_image_mock#10]
I'm trying to test widget that has a Image.network child.

The following log is provided.

```
type 'Null' is not a subtype of type 'List<int>' in type cast

When the exception was thrown, this was the stack:
#1      _MockHttpResponse.drain (package:flutter_test/src/_binding_io.dart:364:22)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:99:24)
<asynchronous suspension>
<asynchronous suspension>
(elided 2 frames from dart:async and package:stack_trace)
```

My test:

```
testWidgets('My new test', (WidgetTester tester) async {
    mockNetworkImagesFor(() async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: ScreenWidget(),
          ),
        ),
      );

      final myImageFinder = find.byKey(const Key('TheImageWidget'));

      expect(myImageFinder, findsOneWidget);

    });
  });
```

In the above sample of code, `ScreenWidget` has a child that is a `Image.network`.

Any thoughts?

**Comment by Add00w** [comment]
> I'm trying to test a widget that has a Image.network child.
> 
> The following log is provided.
> 
> ```
> type 'Null' is not a subtype of type 'List<int>' in type cast
> 
> When the exception was thrown, this was the stack:
> #1      _MockHttpResponse.drain (package:flutter_test/src/_binding_io.dart:364:22)
> #2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:99:24)
> <asynchronous suspension>
> <asynchronous suspension>
> (elided 2 frames from dart:async and package:stack_trace)
> ```
> 
> My test:
> 
> ```
> testWidgets('My new test', (WidgetTester tester) async {
>     mockNetworkImagesFor(() async {
>       await tester.pumpWidget(
>         MaterialApp(
>           home: Scaffold(
>             body: ScreenWidget(),
>           ),
>         ),
>       );
> 
>       final myImageFinder = find.byKey(const Key('TheImageWidget'));
> 
>       expect(myImageFinder, findsOneWidget);
> 
>     });
>   });
> ```
> 
> In the above sample of code, `ScreenWidget` has a child that is a `Image.network`.
> 
> Any thoughts?

Put await infront of mockNetworkImagesFor as follows:

await  mockNetworkImagesFor(() async {
 await tester.pumpWidget(
MaterialApp(
 home: Scaffold(
body: ScreenWidget(),
   ),
 ),
 );

**Comment by campovski** [comment]
Sorry for not responding earlier, I sort of forgot to answer. Yes, the provided answer points out your mistake.
