### ISSUE TITLE
SLNIM-2: Package breaks with Flutter 1.23

### ISSUE THREAD

**Issue by IoanaAlexandru** [stelynx/network_image_mock#2]
Tests using `mockNetworkImagesFor` now fail after upgrading from `1.22.0-12.4.pre` to `1.23.0-18.1.pre`, on the beta channel. This is the error:

<details><summary>Stack trace</summary>

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following ReachabilityError was thrown resolving an image codec:
`null` encountered as case in a switch expression with a non-nullable enum type.

When the exception was thrown, this was the stack:
#0      consolidateHttpClientResponseBytes (package:flutter/src/foundation/consolidate_response.dart:59:3)
#1      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:102:37)
<asynchronous suspension>
#2      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:506:13)
#4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:375:22)
#5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:504:83)
#6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:335:9)
#7      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:465:26)
#8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
#9      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:462:11)
#13     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:454:16)
#14     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:332:5)
#15     DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:258:55)
#16     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:466:20)
#17     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:484:5)
#18     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2081:17)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#24     _RenderListTile.paint.doPaint (package:flutter/src/material/list_tile.dart:1692:17)
#25     _RenderListTile.paint (package:flutter/src/material/list_tile.dart:1695:12)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#28     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:71:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#31     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7320:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#37     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#40     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#51     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#52     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#53     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
#54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#55     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#58     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:642:17)
#59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#61     RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:276:15)
#62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#64     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:646:17)
#65     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:637:7)
#66     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#67     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#68     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#69     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
#70     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#71     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#74     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#75     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#77     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#80     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#83     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#86     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#89     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#91     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#92     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#93     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
#94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#96     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:575:11)
#97     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#98     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#99     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#100    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#101    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#102    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#103    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
#104    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#105    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2616:15)
#106    RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:407:5)
#107    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#108    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#109    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#110    _RenderInkFeatures.paint (package:flutter/src/material/material.dart:551:11)
#111    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#112    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#113    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
#114    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1860:15)
#115    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#116    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#117    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#118    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#119    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#120    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#121    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#122    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#123    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
#124    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#125    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#126    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#127    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
#128    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1111:27)
#129    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:309:5)
#130    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#131    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#132    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:974:9)
#135    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#136    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:961:27)
#137    WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:640:23)
<asynchronous suspension>
#138    WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#141    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#142    WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:634:27)
#143    main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/Users/sako_/StudioProjects/acs-upb-mobile/test/integration_test.dart:926:24)
<asynchronous suspension>
#144    main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/Users/sako_/StudioProjects/acs-upb-mobile/test/integration_test.dart)
#149    HttpOverrides.runZoned (dart:_http/overrides.dart:55:26)
#150    mockNetworkImagesFor (package:network_image_mock/src/network_image_mock.dart:8:24)
#151    main.<anonymous closure>.<anonymous closure> (file:///C:/Users/sako_/StudioProjects/acs-upb-mobile/test/integration_test.dart:920:15)
<asynchronous suspension>
#152    main.<anonymous closure>.<anonymous closure> (file:///C:/Users/sako_/StudioProjects/acs-upb-mobile/test/integration_test.dart)
#153    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#154    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#155    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:794:19)
<asynchronous suspension>
#158    TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:774:14)
#159    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1191:24)
#160    FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#165    withClock (package:clock/src/default.dart:48:10)
#166    FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#171    FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#172    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1188:15)
#173    testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:136:24)
#174    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#175    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#180    Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#181    Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#186    Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#187    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#188    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#193    Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#194    Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#195    Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#202    Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#203    LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#204    RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#209    RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#210    RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#228    _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#229    new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#233    CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#267    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#275    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#276    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#286    _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
#295    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1505:33)
#296    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017:14)
(elided 122 frames from dart:async and package:stack_trace)

Image provider: NetworkImage("https://cdn.worldvectorlogo.com/logos/flutter-logo.svg", scale: 1.0)
Image key: NetworkImage("https://cdn.worldvectorlogo.com/logos/flutter-logo.svg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

**Comment by campovski** [comment]
From quick glimpse at stack trace I could not figure out what could be causing the issue. I will check it out in greater detail tomorrow, however this package should not have any problems with null-safety being added.

In meantime, please try upgrading this package to v1.0.2, it was released yesterday. It should not fix your problems as it seems, but it is worth a try.

**Comment by campovski** [comment]
@IoanaAlexandru After quick research, #1 should fix your problem, therefore just bump this package to `network_image_mock: ^1.0.2` and it should work fine.

**Comment by IoanaAlexandru** [comment]
I just did and it worked, thank you!
